// TODO
// signal is a kind of supplyment for the message, it can only generated by the system and sent between apps and servers
// it is not part of the message, it is a separate entity
// for example, to indicate someone is typing, or a new message is sent, or a new task is created, etc.
